---
title: "Benchmarking efficiency"
author:
- name: William Hutchison
  affiliation: WEHI - Walter and Eliza Hall Institute of Medical Research
  email: hutchison.w@wehi.edu.au
- name: Stefano Mangiola
  affiliation: WEHI - Walter and Eliza Hall Institute of Medical Research
package: tidySpatialExperiment
output:
  BiocStyle::html_document
abstract: |
  Examine the efficiency gains and losses of tidySpatialExperiment.
vignette: |
  %\VignetteIndexEntry{Benchmarking efficiency}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Set up

```{r, message = FALSE, results = FALSE}
# Load libraries
library(tidySpatialExperiment)
library(tibble)
library(dplyr)
library(ggplot2)
library(cowplot)
library(microbenchmark)

# Load data
example(read10xVisium)
```

# Define comparison functions

```{r}
# Select cells based on location
tidy_select <- 
  function() {
    spe |> 
      filter(pxl_col_in_fullres < 4000)
}

base_select <- 
  function() {
    spe_coords <- spatialCoords(spe)
    spe[, spe_coords[, "pxl_col_in_fullres"] < 4000]
}

# Group cells by variable
tidy_group <- 
  function() {
    spe |>
      nest(data = -sample_id)
}

base_group <- 
  function() { 
    split(spe, spe$sample_id)
}

# Plot feature counts per cell
tidy_plot <- 
  function() {
    spe |>
      join_features("ENSMUSG00000051951", shape = "long") |>
      ggplot(aes(x = .cell, y = .abundance_counts)) +
      ggplot2::geom_point()
}

base_plot <- 
  function() {
    spe_counts <- counts(spe)
    plot(spe_counts["ENSMUSG00000051951", ]) 
}

# Aggregate cells by variable
tidy_aggregate <- 
  function() {
    spe |> 
      aggregate_cells(sample_id)
}

base_aggregate <- 
  function() {
    spe_split <- split(spe, spe$sample_id)
    spe_split_counts <- lapply(spe_split, counts)
    lapply(spe_split_counts, rowSums)
}
```

# Summarise findings

```{r, fig.show = "hide"}
# Construct benchmark vectors
operation <- 
  c("Select cells within pixel coordinates", "Split cells by variable", "Plot feature count per cell", "Aggregate cells by variable") |>
  rep(each = 2)

method <- 
  c("tidySpatialExperiment", "SpatialExperiment and base R") |>
  rep(times = 4)

time_elapsed <- 
  microbenchmark(
    tidy_select(),
    base_select(),
    tidy_group(),
    base_group(),
    tidy_plot(),
    base_plot(),
    tidy_aggregate(),
    base_aggregate()
  ) |>
  summary() |>
  pull(mean)

variable_count <- 
  c(0, 1, 0, 0, 0, 1, 0, 2)

line_count <- 
  c(2, 2, 2, 1, 3, 2, 2, 3)

# Create tibble 
tidy_base_benchmark <- 
  tibble(
    operation, 
    method,
    time_elapsed, 
    variable_count, 
    line_count
  )
```

# Plot tidyomics and base R / Bioconductor individually

```{r}
# Create plot
plot_list <-
  list(
    tidy_base_benchmark |>
      ggplot(aes(x = operation, y = line_count, group = method, colour = method)) +
      geom_point() +
      geom_line() + 
      scale_y_continuous(limits = c(2, 4), breaks = c(2, 3, 4)) +
      labs(title = "Number of lines", x = "Operation", y = "Count", colour = "Method") +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=1), legend.position = "bottom"),
    
    tidy_base_benchmark |>
      ggplot(aes(x = operation, y = variable_count, group = method, colour = method)) +
      geom_point() +
      geom_line() + 
      scale_y_continuous(limits = c(0, 3), breaks = c(0, 1, 2, 3)) +
      labs(title = "Number of variables", x = "Operation", y = "Count", colour = "Method") +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=1), legend.position = "bottom"),
    
    tidy_base_benchmark |>
      ggplot(aes(x = operation, y = time_elapsed, group = method, colour = method)) +
      geom_point() +
      geom_line() + 
      scale_y_continuous(limits = c(0, 300), breaks = c(0, 100, 200, 300)) +
      labs(title = "Time elapsed", x = "Operation", y = "Milliseconds", colour = "Method") +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=1), legend.position = "bottom")
  )

plot_grid(plotlist = plot_list, ncol = 3)
```

# Plot tidyomics and base R / Bioconductor differences

```{r}
# Create plot
plot_list <-
  list(
    tidy_base_benchmark |>
      group_by(operation) |>
      summarise(variable_count_difference = variable_count[method == "SpatialExperiment and base R"] - variable_count[method == "tidySpatialExperiment"]) |>
      ggplot(aes(x = operation, y = variable_count_difference, group = 1)) +
      geom_line() +
      geom_point() +
      geom_hline(yintercept = 0, linetype = "dotted") +
      scale_y_continuous(limits = c(-3, 3), breaks = c(-3, 0, 3)) +
      labs(title = "Variable count", x = "Operation", y = "Difference in variable count") +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=1), legend.position = "bottom") +
      annotate(geom = "rect", xmin = -Inf, xmax = Inf, ymin = 0, ymax = Inf, fill = "blue", alpha = 0.2) +
      annotate(geom = "rect", xmin = -Inf, xmax = Inf, ymin = 0, ymax = -Inf, fill = "red", alpha = 0.2),
  
  tidy_base_benchmark |>
    group_by(operation) |>
    summarise(line_count_difference = line_count[method == "SpatialExperiment and base R"] - line_count[method == "tidySpatialExperiment"]) |>
    ggplot(aes(x = operation, y = line_count_difference, group = 1)) +
    geom_line() +
    geom_point() +
    geom_hline(yintercept = 0, linetype = "dotted") +
    scale_y_continuous(limits = c(-3, 3), breaks = c(-3, 0, 3)) +
    labs(title = "Line count", x = "Operation", y = "Difference in line count") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=1), legend.position = "bottom") +
    annotate(geom = "rect", xmin = -Inf, xmax = Inf, ymin = 0, ymax = Inf, fill = "blue", alpha = 0.2) +
    annotate(geom = "rect", xmin = -Inf, xmax = Inf, ymin = 0, ymax = -Inf, fill = "red", alpha = 0.2),
  
  tidy_base_benchmark |>
    group_by(operation) |>
    summarise(time_elapsed_difference = time_elapsed[method == "SpatialExperiment and base R"] - time_elapsed[method == "tidySpatialExperiment"]) |>
    ggplot(aes(x = operation, y = time_elapsed_difference, group = 1)) +
    geom_line() +
    geom_point() +
    geom_hline(yintercept = 0, linetype = "dotted") +
    scale_y_continuous(limits = c(-300, 300), breaks = c(-300, 0, 300)) +
    labs(title = "Time elapsed", x = "Operation", y = "Difference in milliseconds elapsed") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=1), legend.position = "bottom") +
    annotate(geom = "rect", xmin = -Inf, xmax = Inf, ymin = 0, ymax = Inf, fill = "blue", alpha = 0.2) +
    annotate(geom = "rect", xmin = -Inf, xmax = Inf, ymin = 0, ymax = -Inf, fill = "red", alpha = 0.2)
  )

plot_grid(plotlist = plot_list, ncol = 3)
```